<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Destonize</AssemblyName>
    <RootNamespace>Destonize</RootNamespace>
    <ApplicationIcon>..\..\assets\app-icon.ico</ApplicationIcon>
    <UseAppHost>true</UseAppHost>



    <Version>0.0.2</Version>
    <FileVersion>0.0.2</FileVersion>
    <AssemblyVersion>0.0.2</AssemblyVersion>



  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\assets\splash-screen.png" Link="assets\splash-screen.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\assets\app-icon.ico" Link="assets\app-icon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>